version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./code:/code
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
    command: ["runserver", "0.0.0.0:8888"]
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    ports:
      - "5433:5433"
    networks:
      - mynetwork

networks:
  mynetwork: